apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml.tpl
  - service.yaml.tpl
  - configmap.yaml.tpl
  - secret.yaml.tpl
  - hpa.yaml.tpl
  - ingress.yaml.tpl
  - pdb.yaml.tpl

commonLabels:
  app: spec-cc-0104
