apiVersion: v1
kind: Secret
metadata:
  name: spec-cc-0104-secret
  labels:
    app: spec-cc-0104
type: Opaque
stringData:
  # 数据库敏感信息
  DB_PASSWORD: ""
  
  # 认证密钥
  ACCESS_SECRET: "1dde7130712033d52f8e7d2b8e636a29d2c63111c0a32cc6220f38af350f688d"
  
  # Redis 密码 (如果使用)
  REDIS_PASSWORD: ""
