apiVersion: v1
kind: Service
metadata:
  name: spec-cc-0104-api
  labels:
    app: spec-cc-0104
    component: api
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  selector:
    app: spec-cc-0104
    component: api
---
apiVersion: v1
kind: Service
metadata:
  name: spec-cc-0104-api-nodeport
  labels:
    app: spec-cc-0104
    component: api
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888
      protocol: TCP
      name: http
  selector:
    app: spec-cc-0104
    component: api
